[project]
name = "dyndns-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "poggenpower", email = "github@schmu.net" }
]
requires-python = ">=3.14"
dependencies = [
    "watchdog>=4.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
]

[project.scripts]
dyndns-py = "dyndns_py:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
